[package]
name = "theme"
version = "0.1.0"
authors = ["Jérémy DEMANGE <jeremy@scrapfast.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
tokenizers = "0.10.1"
rust-stemmers = "0.1.0"